<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano (Italian)
// Author of the language pack : MyBB Italia
// Language pack translators website : https://www.mybb-it.com/
// Compatible version of MyBB : 1808
// Last edited in MyBB Editor by : chack1172
// Last edited date : Sun, 30 Oct 2016 19:22:34 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'Non hai inserito un nome utente. Inseriscine uno.';
$l['userdata_banned_username'] = 'Il nome utente inserito non può essere registrato. Inseriscine uno differente.';
$l['userdata_bad_characters_username'] = 'Il nome utente inserito contiene alcuni caratteri non validi. Inseriscine uno differente.';
$l['userdata_invalid_username_length'] = 'Il nome utente inserito ha una lunghezza non consentita. Inseriscine uno compreso tra {1} e {2} caratteri.';
$l['userdata_invalid_usertitle_length'] = 'Il nome utente personalizzato inserito ha una lunghezza non consentita. Inseriscine uno più corto di {1} caratteri.';
$l['userdata_username_exists'] = 'Il nome utente inserito è già occupato. Inseriscine uno differente.';
$l['userdata_invalid_password_length'] = 'La password inserita ha una lunghezza non consentita. Inseriscine una compresa tra {1} e {2} caratteri.';
$l['userdata_no_complex_characters'] = 'La password inserita non è abbastanza complessa. Inserisci una password che sia lunga almeno {1} caratteri, e che contenga una lettera maiuscola, una lettera minuscola e un numero.';
$l['userdata_passwords_dont_match'] = 'La password inserita nel campo di conferma non corrisponde a quella inserita precedentemente. Riconferma la tua password.';
$l['userdata_bad_password_security'] = 'La password inserita corrisponde al nome utente o alla email. Si prega di inserire una password più sicura.';
$l['userdata_missing_email'] = 'Non hai inserito un indirizzo e-mail. Inseriscine uno.';
$l['userdata_invalid_email_format'] = 'L\'indirizzo e-mail inserito non è valido. Inseriscine uno corretto.';
$l['userdata_emails_dont_match'] = 'L\'indirizzo e-mail che hai inserito per la conferma non corrisponde con quello inserito precedentemente. Riconferma il tuo indirizzo e-mail.';
$l['userdata_banned_email'] = 'L\'indirizzo e-mail inserito non può essere utilizzato. Inseriscine uno differente.';
$l['userdata_email_already_in_use'] = 'Hai inserito un indirizzo e-mail utilizzato già per un altro utente. Inseriscine uno differente.';
$l['userdata_dob_required'] = 'Non hai selezionato la tua data di nascita. Selezionala per continuare. (Puoi sempre decidere di nascondere la tua data di nascita e la tua età agli altri utenti.';
$l['userdata_invalid_website'] = 'L\'indirizzo web inserito non è valido. Inseriscine uno valido o lascia il campo vuoto.';
$l['userdata_invalid_icq_number'] = 'Il numero ICQ inserito non è valido. Inseriscine uno valido o lascia il campo vuoto.';
$l['userdata_invalid_birthday'] = 'La data di nascita inserita non è valida. Inseriscine una valida o lascia il campo vuoto.';
$l['userdata_invalid_birthday_coppa'] = 'Per verificare la tua et&agrave;, inserisci l\'anno di nascita. Potrai nascondere la tua et&agrave; e la data di nascita dalle opzioni del tuo profilo.';
$l['userdata_invalid_birthday_coppa2'] = 'Devi avere almeno 13 anni per registrarti su questo forum. Per favore contatta un Amministratore';
$l['userdata_invalid_birthday_privacy'] = 'Seleziona un opzione valida per la privacy del compleanno.';
$l['userdata_invalid_referrer'] = 'Il referente inserito non esiste. Inseriscine uno esistente o lascia il campo vuoto.';
$l['userdata_invalid_language'] = 'La lingua selezionata non esiste. Selezionane una esistente.';
$l['userdata_invalid_style'] = 'Lo stile selezionato non è valido. Per favore, scegline uno valido.';
$l['userdata_missing_returndate'] = 'La data di ritorno specificata è incompleta in uno o più campi. Accertati di aver inserito i campi relativi a giorno, mese ed anno.';
$l['userdata_missing_required_profile_field'] = 'Non hai inserito una opzione per il campo "{1}". Riempilo o seleziona una delle opzioni.';
$l['userdata_bad_profile_field_value'] = 'Non hai selezionato una opzione valida per il campo "{1}".';
$l['userdata_bad_profile_field_values'] = 'Non hai selezionato un\'opzione valida per il campo "{1}". Selezionane una tra quelle proposte.';
$l['userdata_max_limit_reached'] = 'Hai inserito un numero di caratteri non valido per il campo "{1}". Compila questo campo con non pi&ugrave; di {2} caratteri.';
$l['userdata_invalid_checkfield'] = 'Sembra che questo modulo sia stato inviato da uno spam bot. Se credi ci sia un errore, contatta l\'amministratore.';
$l['userdata_invalid_postnum'] = 'Il numero dei messaggi che hai inserito non è valido. Inserisci un numero valido oppure lascia il campo vuoto.';
$l['userdata_invalid_threadnum'] = 'Il numero delle discussioni che hai inserito non è valido. Inserisci un numero valido oppure lascia il campo vuoto.';
$l['userdata_too_many_sig_images'] = 'Ci dispiace, non possiamo aggiornare la tua firma perché contiene troppe immagini. Rimuovi alcune immagini dalla tua firma per continuare.';
$l['userdata_too_many_sig_images2'] = '<strong>Nota:</strong> Il numero massimo di immagini nelle firme è {1}.';
$l['userdata_sig_too_long'] = 'Non puoi aggiornare la tua firma perché è troppo lunga. La lunghezza massima per le firme è {1} caratteri.';
$l['userdata_sig_remove_chars_plural'] = 'Rimuovi {1} caratteri e riprova.';
$l['userdata_sig_remove_chars_singular'] = 'Rimuovi 1 carattere e riprova.';
