<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano (Italian)
// Author of the language pack : MyBB Italia
// Language pack translators website : https://www.mybb-it.com/
// Compatible version of MyBB : 1808
// Last edited in MyBB Editor by : chack1172
// Last edited date : Sun, 30 Oct 2016 19:30:08 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Motivo segnalazione:';
$l['report_to_mod'] = 'Segnala questo contenuto ad un moderatore';
$l['close_window'] = 'Chiudi finestra';
$l['report_content'] = 'Segnala contenuto';
$l['report_reason_rules'] = 'Violazione ai regolamenti del forum';
$l['report_reason_post'] = 'Segnala messaggio';
$l['report_reason_profile'] = 'Segnala profilo';
$l['report_reason_reputation'] = 'Segnala reputazione';
$l['report_reason_bad'] = 'Contenuto non appropriato';
$l['report_reason_spam'] = 'Spam';
$l['report_reason_wrong'] = 'Forum sbagliato';
$l['report_reason_other'] = 'Altro';
$l['success_report_voted'] = 'Ti ringraziamo per la collaborazione.<br />Lo staff del forum controllerà al più presto la tua segnalazione.';
$l['error_report_length'] = 'Per favore indica il motivo della tua segnalazione.';
$l['error_invalid_report'] = 'Questo contenuto non esiste o non può essere segnalato.';
$l['error_invalid_report_reason'] = 'Il motivo selezionato non è valido.';
$l['error_comment_required'] = 'Un commento aggiuntivo è richiesto per il motivo selezionato.';
$l['error_report_duplicate'] = 'Questo contenuto è stato già segnalato da un altro utente.';
$l['report_reason_other_description'] = 'Fornisci più informazioni sul motivo per il quale stai segnalando questo contenuto.';
