<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano (Italian)
// Author of the language pack : MyBB Italia
// Language pack translators website : https://www.mybb-it.com/
// Compatible version of MyBB : 1808
// Last edited in MyBB Editor by : chack1172
// Last edited date : Tue, 18 Oct 2016 16:33:03 +0000
// --------------------------------------------------------------------------------

$l['report_reasons'] = 'Motivo Segnalazioni';
$l['report_reasons_desc'] = 'Qui puoi creare e gestire i motivi che possono essere selezionati quando gli utenti segnalano i contenuti.';
$l['add_new_reason'] = 'Aggiungi Nuovo Motivo';
$l['add_new_reason_desc'] = 'Aggiungi un nuovo motivo che gli utenti possono selezionare quando segnalano i contenuti.';
$l['edit_reason'] = 'Modifica Motivo';
$l['edit_reason_desc'] = 'Modifica un motivo che gli utenti possono selezionare quando segnalano i contenuti.';
$l['applies_to'] = 'Applica A';
$l['order'] = 'Ordine';
$l['extra_comment'] = 'Commento Richiesto?';
$l['options'] = 'Opzioni';
$l['delete_reason'] = 'Elimina Motivo';
$l['no_report_reasons'] = 'Non ci sono motivi di segnalazione nel tuo forum in questo momento.';
$l['reason_title'] = 'Titolo';
$l['reason_title_desc'] = 'Inserisci il titolo del motivo per la segnalazione del contenuto.';
$l['requires_extra'] = 'Commento Aggiuntivo Richiesto?';
$l['requires_extra_desc'] = 'Richiedi all\'utente di inserire un commento aggiuntivo quando seleziona quersto motivo?';
$l['save_reason'] = 'Salva Motivo';
$l['content_colon'] = 'Contenuto:';
$l['all_content'] = 'Tutti i contenuti';
$l['select_content'] = 'Seleziona contenuti';
$l['report_content_'] = 'Niente';
$l['report_content_all'] = 'Tutto';
$l['report_content_post'] = 'Messaggio';
$l['report_content_profile'] = 'Profilo';
$l['report_content_reputation'] = 'Reputazione';
$l['report_reason_rules'] = 'Viola Regolamento Forum';
$l['report_reason_bad'] = 'Contenuto Inappropriato';
$l['report_reason_spam'] = 'Contiene Spam';
$l['report_reason_wrong'] = 'Forum Errato';
$l['report_reason_other'] = 'Altro';
$l['default_report_reason'] = 'Predefinito';
$l['custom_report_reason'] = 'Personalizzato';
$l['update_reasons_order'] = 'Aggiorna Ordine Motivi';
$l['error_cannot_modify_reason'] = 'Non puoi modificare questo motivo.';
$l['error_cannot_delete_reason'] = 'Non puoi eliminare questo motivo.';
$l['error_invalid_reason'] = 'Hai selezionato un motivo non valido.';
$l['error_missing_title'] = 'Non hai inserito un titolo a questo motivo.';
$l['error_missing_extra'] = 'Non hai selezionato se vuoi informazioni aggiuntive per questo motivo.';
$l['success_reasons_disporder_updated'] = 'L\'ordine di visualizzazione dei motivi di segnalazione è stato aggiornato.';
$l['success_reason_created'] = 'Il motivo è stato creato con successo.';
$l['success_reason_updated'] = 'Il motivo è stato aggiornato con successo.';
$l['success_reason_deleted'] = 'Il motivo è stato eliminato con successo.';
$l['confirm_reason_deletion'] = 'Sei sicuro di voler eliminare questo motivo?';
