<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano (Italian)
// Author of the language pack : MyBB Italia
// Language pack translators website : https://www.mybb-it.com/
// Compatible version of MyBB : 1808
// Last edited in MyBB Editor by : chack1172
// Last edited date : Tue, 18 Oct 2016 15:34:13 +0000
// --------------------------------------------------------------------------------

$l['configuration'] = 'Configurazione';
$l['bbsettings'] = 'Impostazioni';
$l['banning'] = 'Ban';
$l['custom_profile_fields'] = 'Campi utente personalizzati';
$l['smilies'] = 'Smilies';
$l['word_filters'] = 'Filtri parole';
$l['mycode'] = 'MyCode';
$l['languages'] = 'Lingue';
$l['post_icons'] = 'Icone messaggi';
$l['help_documents'] = 'Documenti di aiuto';
$l['plugins'] = 'Plugins';
$l['attachment_types'] = 'Tipi di allegati';
$l['moderator_tools'] = 'Tools di moderazione';
$l['spiders_bots'] = 'Spiders / Bots';
$l['calendars'] = 'Calendari';
$l['warning_system'] = 'Sistema di avvertimento';
$l['thread_prefixes'] = 'Prefissi discussione';
$l['security_questions'] = 'Domande di sicurezza';
$l['can_manage_settings'] = 'Può gestire le impostazioni?';
$l['can_manage_banned_accounts'] = 'Può gestire gli account bannati?';
$l['can_manage_custom_profile_fields'] = 'Può gestire i campi utente personalizzati?';
$l['can_manage_smilies'] = 'Può gestire gli smilies?';
$l['can_manage_bad_words'] = 'Può gestire gestire le parole filtrate?';
$l['can_manage_custom_mycode'] = 'Può gestire i MyCode?';
$l['can_manage_language_packs'] = 'Può gestire i pacchetti di traduzione?';
$l['can_manage_post_icons'] = 'Può gestire le icone messaggi?';
$l['can_manage_help_documents'] = 'Può gestire i documenti di aiuto?';
$l['can_manage_plugins'] = 'Può gestire i plugins?';
$l['can_manage_attachment_types'] = 'Può gestire i tipi di allegati?';
$l['can_manage_spiders_bots'] = 'Può gestire gli spiders / bots?';
$l['can_manage_calendars'] = 'Può gestire i calendari?';
$l['can_manage_warning_system'] = 'Può gestire il sistema di avvertimento?';
$l['can_manage_mod_tools'] = 'Può gestire i tools di moderazione?';
$l['can_manage_thread_prefixes'] = 'Può gestire i prefissi discussione?';
$l['can_manage_security_questions'] = 'Può gestire le domande di sicurezza?';
$l['report_reasons'] = 'Motivi Segnazione';
$l['can_manage_report_reasons'] = 'Può gestire i motivi delle segnalazioni?';
